/***
 *  Platypus: Page Layout and Typesetting Software (free at platypus.pz.org)
 *
 *  Platypus is (c) Copyright 2006-09 Pacific Data Works LLC. All Rights Reserved.
 *  Licensed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0.html)
 */

package org.pz.platypus;

/**
 *  Enums representing the various input tokens.
 *  Navigation note: error status codes are in Status.java
 *
 *  @author alb
 */
public enum TokenType
{
    // tokens identifiers generated by the initial parser.
    LINE,
    TEXT,
    MACRO_TEXT,
    SYMBOL,
    COMMAND,
    COMPOUND_COMMAND,
    COMPOUND_COMMAND_END,
    REPLACED_COMMAND,
    MACRO,
    LINE_COMMENT,
    BLOCK_COMMENT,
    EOF,

    // command family identifiers for compound commands
	COMMAND_FONT_FAMILY,
//	COMMAND_TABLE_FAMILY,
//	COMMAND_URL_FAMILY,

    ;

}